import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex justify-center min-h-screen w-full">
          <div className="max-w-7xl w-full h-full">
            <NavBar />
            <main className="p-2 sm:p-4">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
